<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Permission::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $updateDate = $createDate = date('Y-m-d H:i:s');
        $permissions = [
            [
                'name'       => 'dashboard_access',
                'title'      => 'Dashboard Access',
                'route_name' => 'dashboard',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // [
            //     'name'       => 'role_permission_access',
            //     'title'      => 'Role and Permission Access',
            //     'route_name' => 'roles',
            //     'permission_type'       => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            [
                'name'       => 'role_access',
                'title'      => 'Role Access',
                'route_name' => 'roles',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_view',
                'title'      => 'Role View',
                'route_name' => 'roles',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_create',
                'title'      => 'Role Create',
                'route_name' => 'roles',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_edit',
                'title'      => 'Role Edit',
                'route_name' => 'roles',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'role_delete',
                'title'      => 'Role Delete',
                'route_name' => 'roles',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'profile_access',
                'title'      => 'Profile Access',
                'route_name' => 'profile',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'profile_view',
                'title'      => 'Profile View',
                'route_name' => 'profile',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'profile_edit',
                'title'      => 'Profile Edit',
                'route_name' => 'profile',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'change_password',
                'title'      => 'Change Password',
                'route_name' => 'profile',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'setting_access',
                'title'      => 'Setting Menu Access',
                'route_name' => 'settings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'setting_edit',
                'title'      => 'Setting Menu Edit',
                'route_name' => 'settings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_create',
                'title'      => 'User Create',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_access',
                'title'      => 'User Access',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_view',
                'title'      => 'User View',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_edit',
                'title'      => 'User Edit',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_delete',
                'title'      => 'User Delete',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'user_status',
                'title'      => 'User Status',
                'route_name' => 'users',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],


            // permission starts
            [
                'name'       => 'permission_access',
                'title'      => 'Permission Access',
                'route_name' => 'categories',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'permission_view',
                'title'      => 'Permission View',
                'route_name' => 'categories',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'permission_create',
                'title'      => 'Permission Create',
                'route_name' => 'categories',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'permission_edit',
                'title'      => 'Permission Edit',
                'route_name' => 'categories',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'permission_delete',
                'title'      => 'Permission Delete',
                'route_name' => 'categories',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            //permission permissions ends

            // Location permission starts
            [
                'name'       => 'location_access',
                'title'      => 'Location Access',
                'route_name' => 'locations',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'location_create',
                'title'      => 'Location Create',
                'route_name' => 'locations',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'location_edit',
                'title'      => 'Location Edit',
                'route_name' => 'locations',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'location_view',
                'title'      => 'Location View',
                'route_name' => 'locations',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'location_delete',
                'title'      => 'Location Delete',
                'route_name' => 'locations',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            //Location permissions ends

            // Service permission starts
            [
                'name'       => 'service_access',
                'title'      => 'Service Access',
                'route_name' => 'services',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_create',
                'title'      => 'Service Create',
                'route_name' => 'services',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_edit',
                'title'      => 'Service Edit',
                'route_name' => 'services',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_view',
                'title'      => 'Service View',
                'route_name' => 'services',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_delete',
                'title'      => 'Service Delete',
                'route_name' => 'services',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            //Service permissions ends

            /* Service booking permissions starts */
            [
                'name'       => 'service_booking_access',
                'title'      => 'Service Booking Access',
                'route_name' => 'services.bookings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_booking_create',
                'title'      => 'Service Booking Create',
                'route_name' => 'services.bookings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_booking_edit',
                'title'      => 'Service Booking Edit',
                'route_name' => 'services.bookings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_booking_view',
                'title'      => 'Service Booking View',
                'route_name' => 'services.bookings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_booking_delete',
                'title'      => 'Service Booking Delete',
                'route_name' => 'services.bookings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Service booking permissions ends */

            /* Society permission starts */
            [
                'name'       => 'society_access',
                'title'      => 'Society Access',
                'route_name' => 'societies',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'society_create',
                'title'      => 'Society Create',
                'route_name' => 'societies',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'society_edit',
                'title'      => 'Society Edit',
                'route_name' => 'societies',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'society_view',
                'title'      => 'Society View',
                'route_name' => 'societies',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'society_delete',
                'title'      => 'Society Delete',
                'route_name' => 'societies',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Society permissions ends */

            /* Building permission starts */
            [
                'name'       => 'building_access',
                'title'      => 'Building Access',
                'route_name' => 'buildings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'building_create',
                'title'      => 'Building Create',
                'route_name' => 'buildings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'building_edit',
                'title'      => 'Building Edit',
                'route_name' => 'buildings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'building_view',
                'title'      => 'Building View',
                'route_name' => 'buildings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'building_delete',
                'title'      => 'Building Delete',
                'route_name' => 'buildings',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Building permissions ends */

            /* Unit permission starts */
            [
                'name'       => 'unit_access',
                'title'      => 'Unit Access',
                'route_name' => 'units',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'unit_create',
                'title'      => 'Unit Create',
                'route_name' => 'units',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'unit_edit',
                'title'      => 'Unit Edit',
                'route_name' => 'units',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'unit_view',
                'title'      => 'Unit View',
                'route_name' => 'units',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'unit_delete',
                'title'      => 'Unit Delete',
                'route_name' => 'units',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Unit permissions ends */

            /* Announcement permission starts */
            [
                'name'       => 'announcement_access',
                'title'      => 'Announcement  Access',
                'route_name' => 'announcements',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_create',
                'title'      => 'Announcement Create',
                'route_name' => 'announcements',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_edit',
                'title'      => 'Announcement  Edit',
                'route_name' => 'announcements',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_view',
                'title'      => 'Announcement View',
                'route_name' => 'announcements',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'announcement_delete',
                'title'      => 'Announcement  Delete',
                'route_name' => 'announcements',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Announcement permissions ends */

            /* Complaints permission starts */
            [
                'name'       => 'complaint_access',
                'title'      => 'Complaint Access',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_create',
                'title'      => 'Complaint Create',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_edit',
                'title'      => 'Complaint Edit',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_view',
                'title'      => 'Complaint View',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_delete',
                'title'      => 'Complaint Delete',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_view_images',
                'title'      => 'Complaint View Images',
                'route_name' => 'complaints',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Complaints permissions ends */
            /* Guards permission starts */
            [
                'name'       => 'guard_access',
                'title'      => 'Guard Access',
                'route_name' => 'guards',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'guard_create',
                'title'      => 'Guard Create',
                'route_name' => 'guards',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'guard_edit',
                'title'      => 'Guard Edit',
                'route_name' => 'guards',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'guard_view',
                'title'      => 'Guard View',
                'route_name' => 'guards',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'guard_delete',
                'title'      => 'Guard Delete',
                'route_name' => 'guards',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Guards permissions ends */
            /* Complaint Types permissions starts */
            [
                'name'       => 'complaint_type_access',
                'title'      => 'Complaint Type Access',
                'route_name' => 'complaint-types',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_type_create',
                'title'      => 'Complaint Type Create',
                'route_name' => 'complaint-types',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_type_edit',
                'title'      => 'Complaint Type Edit',
                'route_name' => 'complaint-types',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_type_view',
                'title'      => 'Complaint Type View',
                'route_name' => 'complaint-types',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'complaint_type_delete',
                'title'      => 'Complaint Type Delete',
                'route_name' => 'complaint-types',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Complaint Types permissions ends */

            /* Residents permissions starts */
            [
                'name'       => 'resident_access',
                'title'      => 'Resident Access',
                'route_name' => 'residents',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_create',
                'title'      => 'Resident Create',
                'route_name' => 'residents',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_edit',
                'title'      => 'Resident Edit',
                'route_name' => 'residents',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_view',
                'title'      => 'Resident View',
                'route_name' => 'residents',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_delete',
                'title'      => 'Resident Delete',
                'route_name' => 'residents',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Residents permissions ends */

            /* Posts permissions starts */
            [
                'name'       => 'post_access',
                'title'      => 'Post Access',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'post_create',
                'title'      => 'Post Create',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'post_edit',
                'title'      => 'Post Edit',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'post_view',
                'title'      => 'Post View',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'post_delete',
                'title'      => 'Post Delete',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'post_comment_access',
                'title'      => 'Post Comment Access',
                'route_name' => 'posts',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            /* Posts permissions ends */

            /* Faqs permissions starts */
            [
                'name'       => 'faq_access',
                'title'      => 'Faq Access',
                'route_name' => 'faqs',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_create',
                'title'      => 'Faq Create',
                'route_name' => 'faqs',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_edit',
                'title'      => 'Faq Edit',
                'route_name' => 'faqs',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_view',
                'title'      => 'Faq View',
                'route_name' => 'faqs',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'faq_delete',
                'title'      => 'Faq Delete',
                'route_name' => 'faqs',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Faqs permissions ends */

            /* Support permissions starts */
            [
                'name'       => 'support_access',
                'title'      => 'Support Access',
                'route_name' => 'supports',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'support_create',
                'title'      => 'Support Create',
                'route_name' => 'supports',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'support_edit',
                'title'      => 'Support Edit',
                'route_name' => 'supports',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'support_view',
                'title'      => 'Support View',
                'route_name' => 'supports',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'support_delete',
                'title'      => 'Support Delete',
                'route_name' => 'supports',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Support permissions ends */

            /* Visitor permissions starts */
            [
                'name'       => 'visitor_access',
                'title'      => 'Visitor Access',
                'route_name' => 'visitors',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'visitor_create',
                'title'      => 'Visitor Create',
                'route_name' => 'visitors',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'visitor_edit',
                'title'      => 'Visitor Edit',
                'route_name' => 'visitors',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'visitor_view',
                'title'      => 'Visitor View',
                'route_name' => 'visitors',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'visitor_delete',
                'title'      => 'Visitor Delete',
                'route_name' => 'visitors',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Support permissions ends */


            [
                'name'       => 'comment_access',
                'title'      => 'Comment Access',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            [
                'name'       => 'comment_approve',
                'title'      => 'Comment Approve',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'comment_create',
                'title'      => 'Comment Create',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'comment_edit',
                'title'      => 'Comment Edit',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'comment_view',
                'title'      => 'Comment View',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'comment_delete',
                'title'      => 'Comment Delete',
                'route_name' => 'comments',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],


            // Amenities
            [
                'name'       => 'amenity_booking_access',
                'title'      => 'Bookings',
                'route_name' => 'amenity.booking',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'amenity_access',
                'title'      => 'Amenity',
                'route_name' => 'amenities',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'amenity_create',
                'title'      => 'Amenity Create',
                'route_name' => 'amenities',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'amenity_edit',
                'title'      => 'Amenity Edit',
                'route_name' => 'amenities',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'amenity_delete',
                'title'      => 'Amenity Delete',
                'route_name' => 'amenities',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'amenity_view',
                'title'      => 'Amenity View',
                'route_name' => 'amenities',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],


            [
                'name'       => 'transaction_access',
                'title'      => 'Transaction',
                'route_name' => 'transactions',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Payment Request
            [
                'name'       => 'payment_request_access',
                'title'      => 'Payment Request Access',
                'route_name' => 'payment-requests',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_request_create',
                'title'      => 'Payment Request Create',
                'route_name' => 'payment-requests',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_request_edit',
                'title'      => 'Payment Request Edit',
                'route_name' => 'payment-requests',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_request_delete',
                'title'      => 'Payment Request Delete',
                'route_name' => 'payment-requests',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_request_view',
                'title'      => 'Payment Request View',
                'route_name' => 'payment-requests',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // [
            //     'name'       => 'feature_access',
            //     'title'      => 'Feature Access',
            //     'route_name' => 'features',
            //     'permission_type' => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            // [
            //     'name'       => 'feature_create',
            //     'title'      => 'Feature Create',
            //     'route_name' => 'features',
            //     'permission_type' => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            // [
            //     'name'       => 'feature_edit',
            //     'title'      => 'Feature Edit',
            //     'route_name' => 'features',
            //     'permission_type' => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            // [
            //     'name'       => 'feature_view',
            //     'title'      => 'Feature View',
            //     'route_name' => 'features',
            //     'permission_type' => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],
            // [
            //     'name'       => 'feature_delete',
            //     'title'      => 'Feature Delete',
            //     'route_name' => 'features',
            //     'permission_type' => 'backend',
            //     'created_at' => $createDate,
            //     'updated_at' => $updateDate,
            // ],

            [
                'name'       => 'payment_method_access',
                'title'      => 'Payment Method Access',
                'route_name' => 'payment-methods',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_method_create',
                'title'      => 'Payment Method Create',
                'route_name' => 'payment-methods',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_method_edit',
                'title'      => 'Payment Method Edit',
                'route_name' => 'payment-methods',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_method_view',
                'title'      => 'Payment Method View',
                'route_name' => 'payment-methods',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'payment_method_delete',
                'title'      => 'Payment Method Delete',
                'route_name' => 'payment-methods',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            /* Providers permissions starts */
            [
                'name'       => 'provider_access',
                'title'      => 'Provider Access',
                'route_name' => 'providers',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'provider_create',
                'title'      => 'Provider Create',
                'route_name' => 'providers',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'provider_edit',
                'title'      => 'Provider Edit',
                'route_name' => 'providers',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'provider_view',
                'title'      => 'Provider View',
                'route_name' => 'providers',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'provider_delete',
                'title'      => 'Provider Delete',
                'route_name' => 'providers',
                'permission_type'       => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Providers permissions ends */


            /* property-types permissions starts */
            [
                'name'       => 'property_type_access',
                'title'      => 'Property Type Access',
                'route_name' => 'property-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_type_create',
                'title'      => 'Property Type Create',
                'route_name' => 'property-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_type_edit',
                'title'      => 'Property Type Edit',
                'route_name' => 'property-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_type_view',
                'title'      => 'Property Type View',
                'route_name' => 'property-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_type_delete',
                'title'      => 'Property Type Delete',
                'route_name' => 'property-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* property-types permissions ends */


            /* Category permissions starts */
            [
                'name'       => 'category_access',
                'title'      => 'Category Access',
                'route_name' => 'categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'category_create',
                'title'      => 'Category Create',
                'route_name' => 'categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'category_edit',
                'title'      => 'Category Edit',
                'route_name' => 'categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'category_view',
                'title'      => 'Category View',
                'route_name' => 'categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'category_delete',
                'title'      => 'Category Delete',
                'route_name' => 'categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* Category permissions ends */

            /* maintenance item permissions starts */
            [
                'name'       => 'maintenance_item_access',
                'title'      => 'Maintenance Item Access',
                'route_name' => 'maintenance-items',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_item_create',
                'title'      => 'Maintenance Item Create',
                'route_name' => 'maintenance-items',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_item_edit',
                'title'      => 'Maintenance Item Edit',
                'route_name' => 'maintenance-items',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_item_view',
                'title'      => 'Maintenance Item View',
                'route_name' => 'maintenance-items',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_item_delete',
                'title'      => 'Maintenance Item Delete',
                'route_name' => 'maintenance-items',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* maintenance item permissions ends */


            [
                'name'       => 'resident_vehicle_access',
                'title'      => 'Resident Vehicle Access',
                'route_name' => 'resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_vehicle_delete',
                'title'      => 'Resident Vehicle Delete',
                'route_name' => 'resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_vehicle_create',
                'title'      => 'Resident Vehicle Create',
                'route_name' => 'resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_vehicle_view',
                'title'      => 'Resident Vehicle View',
                'route_name' => 'resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_vehicle_edit',
                'title'      => 'Resident Vehicle Edit',
                'route_name' => 'resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_pre_approved_vehicle_access',
                'title'      => 'Resident Pre Approved Vehicle Access',
                'route_name' => 'preapproved-resident-vehicles',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // resident daily help
            [
                'name'       => 'resident_daily_help_access',
                'title'      => 'Resident Daily Help Access',
                'route_name' => 'resident-daily-helps',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_daily_help_create',
                'title'      => 'Resident Daily Help Create',
                'route_name' => 'resident-daily-helps',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_daily_help_view',
                'title'      => 'Resident Daily Help View',
                'route_name' => 'resident-daily-helps',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_daily_help_edit',
                'title'      => 'Resident Daily Help Edit',
                'route_name' => 'resident-daily-helps',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'resident_daily_help_delete',
                'title'      => 'Resident Daily Help Delete',
                'route_name' => 'resident-daily-helps',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            /* maintenance Plan permissions starts */
            [
                'name'       => 'maintenance_plan_access',
                'title'      => 'Maintenance Plan Access',
                'route_name' => 'maintenance-plans',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_plan_create',
                'title'      => 'Maintenance Plan Create',
                'route_name' => 'maintenance-plans',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_plan_edit',
                'title'      => 'Maintenance Plan Edit',
                'route_name' => 'maintenance-plans',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_plan_view',
                'title'      => 'Maintenance Plan View',
                'route_name' => 'maintenance-plans',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'maintenance_plan_delete',
                'title'      => 'Maintenance Plan Delete',
                'route_name' => 'maintenance-plans',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* maintenance item permissions ends */

            /* property management permissions starts */
            [
                'name'       => 'property_management_access',
                'title'      => 'Property Management Access',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_management_create',
                'title'      => 'Property Management Create',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_management_edit',
                'title'      => 'Property Management Edit',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_management_view',
                'title'      => 'Property Management View',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_management_delete',
                'title'      => 'Property Management Delete',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'property_management_report',
                'title'      => 'Property Management Report',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            [
                'name'       => 'property_management_view_images',
                'title'      => 'Property Management Report View All Image',
                'route_name' => 'property-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* property management permissions ends */

            /* deliveryType permissions starts */
            [
                'name'       => 'delivery_type_access',
                'title'      => 'Delivery Type Access',
                'route_name' => 'delivery-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_type_create',
                'title'      => 'Delivery Type Create',
                'route_name' => 'delivery-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_type_edit',
                'title'      => 'Delivery Type Edit',
                'route_name' => 'delivery-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_type_view',
                'title'      => 'Delivery Type View',
                'route_name' => 'delivery-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_type_delete',
                'title'      => 'Delivery Type Delete',
                'route_name' => 'delivery-types',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* deliveryType permissions ends */

            /* deliveryType permissions starts */
            [
                'name'       => 'delivery_management_access',
                'title'      => 'Delivery Management Access',
                'route_name' => 'delivery-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_management_create',
                'title'      => 'Delivery Management Create',
                'route_name' => 'delivery-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_management_edit',
                'title'      => 'Delivery Management Edit',
                'route_name' => 'delivery-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_management_view',
                'title'      => 'Delivery Management View',
                'route_name' => 'delivery-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'delivery_management_delete',
                'title'      => 'Delivery Management Delete',
                'route_name' => 'delivery-managements',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            /* deliveryType permissions ends */

            [
                'name'       => 'transaction_report_access',
                'title'      => 'Transaction Report Access',
                'route_name' => 'transaction-reports',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            [
                'name'       => 'admin_message_access',
                'title'      => 'Admin Message Access',
                'route_name' => 'messages',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // camera permissions
            [
                'name'       => 'camera_access',
                'title'      => 'Camera Access',
                'route_name' => 'cameras',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'camera_create',
                'title'      => 'Camera Create',
                'route_name' => 'cameras',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'camera_view',
                'title'      => 'Camera View',
                'route_name' => 'cameras',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'camera_edit',
                'title'      => 'Camera Edit',
                'route_name' => 'cameras',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'camera_delete',
                'title'      => 'Camera Delete',
                'route_name' => 'cameras',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // end camera permissions

            [
                'name'       => 'notification_access',
                'title'      => 'Notification Access',
                'route_name' => 'notifications',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],

            // Service ategory permission starts
            [
                'name'       => 'service_category_access',
                'title'      => 'Service Category Access',
                'route_name' => 'service-categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_category_create',
                'title'      => 'Service Category Create',
                'route_name' => 'service-categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_category_edit',
                'title'      => 'Service Category Edit',
                'route_name' => 'service-categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_category_view',
                'title'      => 'Service Category View',
                'route_name' => 'service-categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'service_category_delete',
                'title'      => 'Service Category Delete',
                'route_name' => 'service-categories',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            //Service category permissions ends

            // ai box notification
            [
                'name'       => 'aibox_notification_access',
                'title'      => 'AI Box Notification Access',
                'route_name' => 'ai-box-notifications',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'aibox_notification_view',
                'title'      => 'AI Box Notification View',
                'route_name' => 'ai-box-notifications',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'aibox_notification_view_image',
                'title'      => 'AI Box Notification View Image',
                'route_name' => 'ai-box-notifications',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            [
                'name'       => 'aibox_notification_view_video',
                'title'      => 'AI Box Notification View Video',
                'route_name' => 'ai-box-notifications',
                'permission_type' => 'backend',
                'created_at' => $createDate,
                'updated_at' => $updateDate,
            ],
            // ai box notification end

        ];
        Permission::insert($permissions);
    }
}
